### ISSUE TITLE
devnet-0

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#8605] opened 2024-06-04 21:34 UTC
Ship devnet-0 support

**Comment by onbjerg** [comment] 2024-06-04 22:23
dupe of https://github.com/paradigmxyz/reth/issues/7363?

**Comment by Rjected** [comment] 2024-06-12 21:20
Closing in favor of devnet-1 planning: https://github.com/paradigmxyz/reth/issues/8788

**Closed by Rjected** 2024-06-12 21:20 UTC
