### ISSUE TITLE
Tracking Optimism RPC support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9294] opened 2024-07-04 09:26 UTC
### Describe the feature

Add standalone OP RPC support

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/9296
- [ ] https://github.com/paradigmxyz/reth/issues/9323
- [ ] https://github.com/paradigmxyz/reth/issues/9325
```

**Comment by emhane** [comment] 2024-07-26 17:33
duplicate of https://github.com/paradigmxyz/reth/issues/8988

**Closed by emhane** 2024-07-26 17:33 UTC
Labels: C-enhancement, C-tracking-issue, A-op-reth
