### ISSUE TITLE
Add db cursor reverse iterator

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#331] opened 2022-12-05 11:05 UTC
mdbx does have support for it, it just needs to be added to `DbDupCursorRO` and `DbCursorRO`. It would make iteration over some tables easier.

**Comment by rkrasiuk** [comment] 2022-12-13 15:59
@rakita can you pls clarify that this is an issue tracker for the reverse walker, not the reverse cursor?

**Comment by onbjerg** [comment] 2023-01-13 10:18
Closing as a dupe of #837

**Closed by onbjerg** 2023-01-13 10:18 UTC
Labels: A-db
