### ISSUE TITLE
trace_call  & trace_callMany fails if nonce is provided

### ISSUE THREAD

**Issue by syahrul12345** [paradigmxyz/reth#3604] opened 2023-07-05 14:14 UTC
### Describe the bug

I am using trace_call to replay and debug state changes in a transaction. However, when i specify the exact same nonce used in the confirmed transaction in trace_call or trace_callMany, reth returns a 'nonce too high'.

Might be related to #3535 

### Steps to reproduce

Consider this payload:
Confirmed transaction: 
https://etherscan.io/tx/0x5f8c96142435c2859f5b923c50ed1769c9ccc433f564fbeb103c454706093762

```
{
    "jsonrpc": "2.0",
    "method": "trace_call",
    "params": [
        {
            "from": "0xfa9f7a1cbfbcb688729c522b4f0905ccf4d26d25",
            "to": "0xa2332ddbb19a71533549782abc879eebbf38d67d",
            "nonce": "0xab22"
        },
        [
            "stateDiff"
        ],
        "0x10cfabf"
    ],
    "id": "1"
}
```

# Erigon Response
```
{
    "jsonrpc": "2.0",
    "id": "1",
    "result": {
        "output": "0x",
        "stateDiff": {
            "0xfa9f7a1cbfbcb688729c522b4f0905ccf4d26d25": {
                "balance": {
                    "*": {
                        "from": "0x1490ce321125c6fecd",
                        "to": "0x1490ca30353da80285"
                    }
                },
                "code": "=",
                "nonce": {
                    "*": {
                        "from": "0xab21",
                        "to": "0xab22"
                    }
                },
                "storage": {}
            }
        },
        "trace": [],
        "vmTrace": null
    }
}
```

# Reth response
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32003,
        "message": "nonce too high"
    },
    "id": "1"
}
```

### What version/commit are you on?

a932e2f1

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by syahrul12345** [comment] 2023-07-05 14:16
This works:
```
{
    "jsonrpc": "2.0",
    "method": "trace_call",
    "params": [
        {
            "from": "0xfa9f7a1cbfbcb688729c522b4f0905ccf4d26d25",
            "to": "0xa2332ddbb19a71533549782abc879eebbf38d67d",
            "nonce": "0xab21"
        },
        [
            "stateDiff"
        ],
        "0x10cfabf"
    ],
    "id": "1"
}
```

**Comment by syahrul12345** [comment] 2023-07-05 14:22
However, this nonce - 1 trick seems inconsistent and doesnt always work:
https://etherscan.io/tx/0xe0bcf1fffc1c46b1469db48bcc575372343293b42f0dcf64024b1027971961d8
```
//Works, dont subtract 1 from nonce in confimred tx
{
    "jsonrpc": "2.0",
    "method": "trace_call",
    "params": [
        {
            "from": "0xa9232040bf0e0aea2578a5b2243f2916dbfc0a69",
            "to": "0x550f589100e379c8530c0564566d6e270ff13457",
            "nonce": "0x102"
        },
        [
            "stateDiff"
        ],
        "0x10cfabf"
    ],
    "id": "1"
}
//If we subtract 1, we get nonce too low
{
    "jsonrpc": "2.0",
    "method": "trace_call",
    "params": [
        {
            "from": "0xa9232040bf0e0aea2578a5b2243f2916dbfc0a69",
            "to": "0x550f589100e379c8530c0564566d6e270ff13457",
            "nonce": "0x101"
        },
        [
            "stateDiff"
        ],
        "0x10cfabf"
    ],
    "id": "1"
}
```

**Comment by mattsse** [comment] 2023-07-05 14:27
there are 3 transactions from that sender in the block:

https://etherscan.io/address/0xfa9f7a1cBfBCB688729c522b4F0905CcF4d26D25

and you picked the one in the middle, that's why nonce-1 works

**Comment by mattsse** [comment] 2023-07-05 14:32
closing this because this is the intended behavior if traced on the parent block.

I think you're looking for `trace_replayTransaction` instead

**Closed by mattsse** 2023-07-05 14:32 UTC
Labels: C-bug, A-rpc

**Comment by gakonst** [comment] 2023-07-05 19:02
@syahrul12345 confirming our answer makes sense?

**Comment by syahrul12345** [comment] 2023-07-05 20:57
yeap, but im wondering if inconsistencies between node implementations is common throughout apis, as it looks like erigon allows us to use a higher nonce than expected
