### ISSUE TITLE
Error: failed to commit transaction changes (998)

### ISSUE THREAD

**Issue by lucyzhang314** [paradigmxyz/reth#5964] opened 2024-01-06 16:32 UTC
### Describe the bug

![image](https://github.com/paradigmxyz/reth/assets/40690755/55f1dd83-9d9d-4aa2-8d86-8164e2525ed9)

### Steps to reproduce

.\reth.exe node --datadir . --debug.tip 0xbd5bd619820ba37a6d123b207196f81b1c57b879e95a05f39e00747cd68f3cf4 --authrpc.port 8552

### What version/commit are you on?

reth Version: 0.1.0-alpha.13 Commit SHA: a5a0fff51 Build Timestamp: 2024-01-06T16:22:17.010024400Z Build Features: default,jemalloc Build Profile: release

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

 cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by DaniPopes** [comment] 2024-01-22 16:16
Duplicate of https://github.com/paradigmxyz/reth/issues/3793.

**Closed by DaniPopes** 2024-01-22 16:16 UTC
Labels: C-bug, S-needs-triage
