### ISSUE TITLE
Cant start reth.exe on windows 10 in powershell

### ISSUE THREAD

**Issue by Ajes1337** [paradigmxyz/reth#3306] opened 2023-06-21 17:27 UTC
### Describe the bug

![image](https://github.com/paradigmxyz/reth/assets/11885892/91f5268e-4ae9-49dc-9016-6ee4118bdfc6)

### Steps to reproduce

install windows 10
download windows build from github
run the node from powershell with command ".\reth.exe node"

### Node logs

```text
PS C:\reth> .\reth.exe node
2023-06-21T17:21:43.080472Z  INFO reth::cli: reth 0.1.0-alpha.1 (b245193) starting
2023-06-21T17:21:43.080895Z  INFO reth::cli: Configuration loaded path="C:\\Users\\Admin\\AppData\\Roaming\\reth\\mainnet\\reth.toml"
2023-06-21T17:21:43.081022Z  INFO reth::cli: Opening database path="C:\\Users\\Admin\\AppData\\Roaming\\reth\\mainnet\\db"
Error: Failed to open database: -30784

Location:
    /project/crates/staged-sync/src/utils/init.rs:33:14
PS C:\reth>
```

### What version/commit are you on?

0.1.0-alpha.1

### What database version are you on?

?

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by onbjerg** [comment] 2023-06-21 19:45
Can you try creating the path it tries to open? If that fixes it, then the solution is to create the database path (if it doesn't exist) before opening. This already happens on macOS and Linux I guess, but Windows is always an edge case...

**Comment by Ajes1337** [comment] 2023-06-22 06:14
The path was already created when I looked into it, here is screenshot: 
![image](https://github.com/paradigmxyz/reth/assets/11885892/745679aa-9b6e-4355-b60c-279502f2577e)

**Comment by 0xDaizz** [comment] 2023-07-03 02:26
do you have any solution for this? I have the same issue

**Comment by shekhirin** [comment] 2023-07-04 14:35
@Ajes1337 @0xDaizz we've just added more database logs, can you please try running reth from the latest `main` with `--db.log-level error` CLI argument?
```console
.\reth.exe node --db.log-level error
```

**Comment by 0xDaizz** [comment] 2023-07-05 18:23
@shekhirin how can I build the exe file with the newest branch? when I compile the compiler throws a lot of errors..

**Comment by onbjerg** [comment] 2023-07-05 21:36
@0xDaizz Just build from main, unfortunately the Windows release is borked because Windows is Windows. I am working on a fix, but it definitely works when compiling manually now after #3608

No need to add `--db.log-level`, I know what the underlying issue is.

Thanks for reporting this bug :)

**Comment by Ajes1337** [comment] 2023-07-08 06:04
I still have this error in Alpha2 release, also have the error with WSL2

![image](https://github.com/paradigmxyz/reth/assets/11885892/a6e7a574-f8e1-4d34-baec-452ce0a435bf)

**Comment by Ajes1337** [comment] 2023-07-09 17:49
reth is working now on WSL2 Ubuntu on windows 10, I had to upgrade from WSL1 to WSL2 👍

**Comment by 0xDaizz** [comment] 2023-07-09 17:52
> reth is working now on WSL2 Ubuntu on windows 10, I had to upgrade from WSL1 to WSL2 👍

Did you successfully finish syncing? 
I have had some Bus error issues during execution phase several times.

https://github.com/paradigmxyz/reth/issues/3293

**Comment by Ajes1337** [comment] 2023-07-09 18:11
> 

I have first just started syncing on WSL2, so cant say much yet

**Comment by gakonst** [comment] 2023-07-10 14:05
Closing as @Ajes1337 confirmed in the Reth Telegram chat that he was actually running WSLv1 instead of v2. @0xDaizz pls confirm you're on WSLv2? Else we can re-open.

**Closed by gakonst** 2023-07-10 14:05 UTC
Labels: C-bug, O-windows, S-needs-investigation, A-db

**Comment by 0xDaizz** [comment] 2023-07-23 08:03
@gakonst 

on windows 10, still this error keeps me away from the node.

```
PS C:\Users\HW\Documents\reth-v0.1.0-alpha.4-x86_64-pc-windows-gnu> ./reth node
2023-07-23T08:01:28.877242Z  INFO reth::cli: reth 0.1.0-alpha.4 (b2b2cbe) starting
2023-07-23T08:01:28.878019Z  INFO reth::cli: Configuration loaded path="C:\\Users\\HW\\AppData\\Roaming\\reth\\mainnet\\reth.toml"
2023-07-23T08:01:28.878065Z  INFO reth::cli: Opening database path="C:\\Users\\HW\\AppData\\Roaming\\reth\\mainnet\\db"
Error: Failed to open database: -30784

Location:
    /project/crates/storage/db/src/lib.rs:125:18
PS C:\Users\HW\Documents\reth-v0.1.0-alpha.4-x86_64-pc-windows-gnu>
```

Used the pre-made binary on the reth github.

**Comment by 0xDaizz** [comment] 2023-07-24 10:49
Confirmed that this issue can be solved by building my own binary via ```$env:RUSTFLAGS="-C target-cpu=native"; cargo build --profile maxperf```. sorry for bothering with Windows x(
