### ISSUE TITLE
Execution stage very slow and only using single core

### ISSUE THREAD

**Issue by kaliubuntu0206** [paradigmxyz/reth#4465] opened 2023-09-03 11:37 UTC
### Describe the bug

Hello,

While syncing RETH with the `--full` sync mode, it only uses a single core and it is very slow.

Should any optimizations could be applied here?

Thanks.

### Steps to reproduce

Syncing `reth` with the `--full` sync mode

### Node logs

```text
Stage committed progress pipeline_stages=5/13 stage=Execution block=2456857 checkpoint=0.3% eta=12days 15h 36m 27s
Status connected_peers=15 stage=Execution checkpoint=0.3% eta=12days 15h 35m 51s
```

### Platform(s)

Linux (x86)

CPU: Xeon E-2286G with 32G memory

Disk: Intel SSD with more than 300MB/s

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment] 2023-09-03 14:31
execution is inherently sequential, there's no way to make this process multicore without redesigning how execution works.

I'm closing this because this is the expected behaviour, however parallel evm is still being investigated

**Closed by mattsse** 2023-09-03 14:31 UTC
Labels: C-bug, S-needs-triage
