### ISSUE TITLE
Docker throws error on build

### ISSUE THREAD

**Issue by mingram-galaxy** [paradigmxyz/reth#7196] opened 2024-03-18 16:26 UTC
### Describe the bug

Building the docker image locally from the Dockerfile throws a dependency error that does not appear in building from source. 

`=> ERROR [builder 4/5] RUN cargo build --profile release --features "" -  0.5s 
`------                                                                          
 > [builder 4/5] RUN cargo build --profile release --features "" --no-default-features --locked --bin reth:                                                     
0.125     Updating crates.io index                                              
0.126     Updating git repository `https://github.com/alloy-rs/alloy`           
0.519 error: failed to get `alloy-eips` as a dependency of package `reth-primitives v0.2.0-beta.3 (/app/crates/primitives)`
0.519 
0.519 Caused by:
0.519   failed to load source for dependency `alloy-eips`
0.519 
0.519 Caused by:
0.519   Unable to update https://github.com/alloy-rs/alloy?rev=410850b#410850b3
0.519 
0.519 Caused by:
0.519   failed to clone into: /usr/local/cargo/git/db/alloy-805bdb2c8d2cb5fa
0.519 

Looking at the alloy repo, the alloy-eips [crate](https://github.com/alloy-rs/alloy/blob/main/crates/alloy/crates/eips) throws a 404. 

### Steps to reproduce

docker build . -t reth:local

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

0.2.0-beta.3

### What database version are you on?

2

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by shekhirin** [comment] 2024-03-18 19:43
Can't reproduce this, and it seems like the error isn't coming from an unexisting crate. The links in alloy repo are indeed need an update (cc @DaniPopes), but I can successfully download all dependencies.

I found this https://github.com/cargo-generate/cargo-generate/issues/168#issuecomment-520065102 git-related issue, can you try it?

**Comment by onbjerg** [comment] 2024-04-02 18:21
Hi @mingram-galaxy, closing this as I can't reproduce it either. If it's still an issue, please re-open it and flag us

**Closed by onbjerg** 2024-04-02 18:21 UTC
Labels: C-bug
