### ISSUE TITLE
Database Commit error code: 998

### ISSUE THREAD

**Issue by ControlCplusControlV** [paradigmxyz/reth#3793] opened 2023-07-15 15:31 UTC
### Describe the bug

Ran into an issue syncing reth + lighthouse on goerli, each being cloned from latest (and stable on lighthouse), on Windows.

### Steps to reproduce

1. `lighthouse bn --network goerli --checkpoint-sync-url https://goerli.checkpoint-sync.ethpandaops.io --execution-endpoint http://localhost:8551 --execution-jwt .\secrets\jwt.hex`
2. `reth node --chain goerli --authrpc.jwtsecret .\secrets\jwt.hex --authrpc.addr 127.0.0.1 --authrpc.port 8551`

after some time ran into issues, *note, I left my node running last night and when I woke up terminal seemed to have crashed, had used same commands but could've been some kind of corrupted db

### Node logs

```text
2023-07-15T15:24:31.440934Z  INFO reth::node::events: Executing stage pipeline_stages=2/13 stage=TotalDifficulty from=9347975 checkpoint=100.0% eta=unknown
2023-07-15T15:24:31.441091Z  INFO reth::node::events: Stage finished executing pipeline_stages=2/13 stage=TotalDifficulty block=9347975 checkpoint=100.0% eta=unknown
2023-07-15T15:24:31.441190Z  INFO reth::node::events: Executing stage pipeline_stages=3/13 stage=Bodies from=3450000 checkpoint=36.9% eta=unknown
2023-07-15T15:24:31.441233Z  INFO downloaders::bodies: Downloading bodies 3450001..=9347975 distance=5897974
2023-07-15T15:24:33.090370Z  INFO net: Session established remote_addr=13.42.4.128:30303 client_version=Geth/v1.11.6-stable/linux-amd64/go1.20.3 peer_id=0x592916e9808f0f558a93518fc6d18e97f83bc79b95a4075695b4a2d78189219f6484acdefcb20cdfa04db6dbfcb513b928e18e9739afe9f738908bcf2190ee11 total_active=1
2023-07-15T15:24:34.264201Z  INFO net: Session established remote_addr=65.21.196.48:30305 client_version=Geth/v1.11.6-stable-ea9e62ca/linux-amd64/go1.20.3 peer_id=0x4abf75fb612753b1e4e1b1ffec6dc9af0b8ffda00758e1c2ddf7e79830eaeb0eae933ed89f067f7671ce8cafbfd2d18623b7b727c2d08af513c64ddf4e7bf798 total_active=2
2023-07-15T15:24:34.970126Z  INFO net: Session established remote_addr=51.15.142.158:30303 client_version=besu/v23.4.1/linux-x86_64/openjdk-java-17 peer_id=0xb860febca5939733d15b699e61040da398b5f907671b8339eaac325cbe375cf9103fa9ee8d6bf385e48a3e70f1e99f55d5a82807438e179dcebc05ef715e756f total_active=2
2023-07-15T15:24:35.567492Z  INFO net: Session established remote_addr=54.180.2.59:30303 client_version=Geth/v1.11.6-stable/linux-amd64/go1.20.3 peer_id=0xfc35f8a83512e25b01c76872061689cf6fa86bc3c8d564b1422721d9c3cb2c8de4bb9fc691879d9dae650931e97b057b1f5dce505ec3849d056a5027d27eb33d total_active=2
2023-07-15T15:24:36.720003Z  INFO net: Session established remote_addr=35.207.134.193:30303 client_version=Geth/v1.10.23-stable-d901d853/linux-amd64/go1.17.12 peer_id=0x2beadd3fa07e5db27c8b8a23136bc46ee2e0b5e770b5edcc53635bd55736cdf8b540581915fe51259d8bb11855aa100c966b71aad5b8f5e7a12bcea2b768b1cd total_active=3
2023-07-15T15:25:01.437888Z  INFO reth::cli: Status connected_peers=2 stage=Bodies checkpoint=36.9% eta=unknown
2023-07-15T15:25:16.389011Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies block=3460000 checkpoint=37.0% eta=unknown
Error: An interface error occurred.

Caused by:
    Database commit error code: 998

Location:
    bin\reth\src\node\mod.rs:439:9
```

Error from lighthouse was
```
Jul 15 15:25:46.498 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:46.500 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:46.501 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:46.503 ERRO Unable to get transition config         error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
Jul 15 15:25:46.504 WARN Error whilst processing payload status  error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
Jul 15 15:25:46.505 ERRO Failed to check transition config       error: EngineError(Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }), service: exec
Jul 15 15:25:46.506 WARN Failed to update head on execution engines, error: ExecutionForkChoiceUpdateFailed(EngineError(Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }))
Jul 15 15:25:47.503 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:47.504 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:47.506 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:25:54.007 INFO Syncing                                 est_time: --, distance: 77 slots (15 mins), peers: 3, service: slot_notifier
Jul 15 15:25:54.010 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:25:55.454 INFO UPnP not available                      error: IO error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060), service: UPnP
Jul 15 15:25:59.515 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:06.006 INFO Syncing                                 est_time: --, distance: 78 slots (15 mins), peers: 9, service: slot_notifier
Jul 15 15:26:06.008 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:26:10.438 WARN Error connecting to eth1 node endpoint  endpoint: http://localhost:8551/, auth=true, service: deposit_contract_rpc
Jul 15 15:26:10.439 ERRO Error updating deposit contract cache   error: Invalid endpoint state: RequestFailed("eth_chainId call failed HttpClient(url: http://localhost:8551/, kind: request, detail: error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061))"), retry_millis: 60000, service: deposit_contract_rpc
Jul 15 15:26:11.518 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:18.000 INFO Syncing                                 est_time: --, distance: 79 slots (15 mins), peers: 11, service: slot_notifier
Jul 15 15:26:18.002 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:26:23.525 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:30.001 INFO Syncing                                 est_time: --, distance: 80 slots (16 mins), peers: 11, service: slot_notifier
Jul 15 15:26:30.003 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:26:35.534 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:42.003 INFO Syncing                                 est_time: --, distance: 81 slots (16 mins), peers: 11, service: slot_notifier
Jul 15 15:26:42.006 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:26:47.507 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:47.508 ERRO Unable to get transition config         error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
Jul 15 15:26:47.510 ERRO Failed to check transition config       error: EngineError(Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }), service: exec
Jul 15 15:26:47.533 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:48.513 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:26:54.000 INFO Syncing                                 est_time: --, distance: 82 slots (16 mins), peers: 18, service: slot_notifier
Jul 15 15:26:54.003 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:26:59.540 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:06.004 INFO Syncing                                 est_time: --, distance: 83 slots (16 mins), peers: 17, service: slot_notifier
Jul 15 15:27:06.006 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:27:10.420 WARN Error connecting to eth1 node endpoint  endpoint: http://localhost:8551/, auth=true, service: deposit_contract_rpc
Jul 15 15:27:10.421 ERRO Error updating deposit contract cache   error: Invalid endpoint state: RequestFailed("eth_chainId call failed HttpClient(url: http://localhost:8551/, kind: request, detail: error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061))"), retry_millis: 60000, service: deposit_contract_rpc
Jul 15 15:27:11.544 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:18.006 INFO Syncing                                 est_time: --, distance: 84 slots (16 mins), peers: 18, service: slot_notifier
Jul 15 15:27:18.008 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:27:23.546 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:30.000 INFO Syncing                                 est_time: --, distance: 85 slots (17 mins), peers: 18, service: slot_notifier
Jul 15 15:27:30.002 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:27:35.549 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:42.000 INFO Syncing                                 est_time: --, distance: 86 slots (17 mins), peers: 18, service: slot_notifier
Jul 15 15:27:42.003 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Jul 15 15:27:47.553 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:48.528 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:48.530 ERRO Unable to get transition config         error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
Jul 15 15:27:48.531 ERRO Failed to check transition config       error: EngineError(Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }), service: exec
Jul 15 15:27:49.536 ERRO Error during execution engine upcheck   error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 15 15:27:54.000 INFO Syncing                                 est_time: --, distance: 87 slots (17 mins), peers: 23, service: slot_notifier
Jul 15 15:27:54.002 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
```

### Platform(s)

Windows (x86)

### What version/commit are you on?

reth Version: 0.1.0-alpha.3 Commit SHA: c1b1eac5 Build Timestamp: 2023-07-15T03:22:44.069834700Z Build Features: default,jemalloc Build Profile: release

### What database version are you on?

```
PS C:\Users\ControlCplusControlV\Code\node> reth db version
Current database version: 1
Local database version: 1
```

### If you've built Reth from source, provide the full command you used

`cargo install --locked --path bin/reth --bin reth`

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by ControlCplusControlV** [comment] 2023-07-15 15:32
Could be because of jemalloc maybe? Will attempt to remove and reproduce

**Comment by gakonst** [comment] 2023-07-15 17:44
Hmm you shouldn't hvae jemalloc I though: https://github.com/paradigmxyz/reth/commit/c0cafc7a4f54f66ec450551f7da0d0561b7ad43a

Have not seen this error before. Please try re-compiling w/o jemalloc or using any of the released binaries for windows!

**Comment by onbjerg** [comment] 2023-07-19 13:44
@ControlCplusControlV Do you have jemalloc metrics exposed on Prometheus with non-0 values? If so, we somehow ended up building jemalloc into Windows

**Comment by ControlCplusControlV** [comment] 2023-07-19 18:52
Sorry been busy, will investigate this later today

**Comment by gakonst** [comment] 2023-07-20 20:22
Roger - any news? Thanks for looking into this.

**Comment by 0xDaizz** [comment] 2023-07-24 11:38
I tried without jemalloc, same error occured.
```
2023-07-24T11:34:24.567961Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies block=1429000 checkpoint=8.0% eta=2m 13s
2023-07-24T11:34:24.577212Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies block=1430000 checkpoint=8.1% eta=2m 31s
2023-07-24T11:34:24.618517Z  INFO reth::cli: Wrote network peers to file peers_file="../data/reth_data\\known-peers.json"
Error: An interface error occurred.

Caused by:
    Database commit error code: 998

Location:
    bin\reth\src\node\mod.rs:441:9
```

built with this command: ```$env:RUSTFLAGS="-C target-cpu=native"; cargo build --profile maxperf```

**Comment by 0xDaizz** [comment] 2023-08-15 22:53
> Roger - any news? Thanks for looking into this.

387000 checkpoint=13.4% eta=unknown
2023-08-15T16:30:38.104117Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies block=2388000 checkpoint=13.4% eta=unknown
2023-08-15T16:30:39.631085Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies block=2389000 checkpoint=13.4% eta=unknown
Error: An interface error occurred.

Caused by:
    Database commit error code: 998


Still same error on alpha.6.

**Comment by gakonst** [comment] 2023-08-15 23:27
@0xDaizz what platform are you on? can you share more context on this?

**Comment by 0xDaizz** [comment] 2023-08-15 23:34
> @0xDaizz what platform are you on? can you share more context on this?

Currently running it on Windows 10, by building the binary via the command described up there.(cargo build --profile maxperf)

I ran the node then after some time passed the node stops with error 998.

**Comment by 0xDaizz** [comment] 2023-08-15 23:36
> @0xDaizz what platform are you on? can you share more context on this?

the error occured on the file of bin/reth/src/node/mod.rs 509th line.

**Comment by 0xmp** [comment] 2023-08-26 18:16
Same issue here, fresh install on windows 10 with reth and lighthouse, both built from sources. 

> the error occured on the file of bin/reth/src/node/mod.rs 502nd line.

Same file but for me line 507, the file may have changed in the meantime

**Comment by ControlCplusControlV** [comment] 2023-09-01 21:18
@gakonst can confirm this occurs without jemalloc, can try to do some more testing on windows, but FWIW I have just transitioned to an m2 max for running things which fixed my issues

**Comment by kaliubuntu0206** [comment] 2023-12-10 12:08
This is still a problem with latest reth version. To reproduce

1. Install Visual Studio Tools

2. Installed chocolatey package manager

3. Installed mingw, make, cmake, llvm via chocolatey

4. Installed latest Rust

5. Built using `cargo build --release` command

6. Running Reth with the following

```
reth node ^
  --chain="holesky" ^
  --authrpc.jwtsecret="jwt.hex" ^
  --http ^
  --color="never" ^
  -vvvvv
```

The console output

```
2023-12-10T11:50:43.180693Z TRACE loop{i=0 current="Nibbles(\"0800\")" build_extensions=false}: trie::hash_builder: resizing tree/hash masks new_len=0 old_tree_mask_len=2 old_hash_mask_len=2
2023-12-10T11:50:43.180739Z TRACE loop{i=0 current="Nibbles(\"0800\")" build_extensions=false}: trie::hash_builder: 0 or 1 state masks means we have no more elements to process
2023-12-10T11:50:43.181413Z TRACE downloaders::bodies: Requesting bodies request_len=200
2023-12-10T11:50:43.181926Z TRACE downloaders::bodies: Requesting bodies request_len=200
2023-12-10T11:50:43.182428Z TRACE downloaders::bodies: Requesting bodies request_len=200
2023-12-10T11:50:43.182897Z TRACE downloaders::bodies: Requesting bodies request_len=200
2023-12-10T11:50:43.183399Z TRACE downloaders::bodies: Requesting bodies request_len=200
2023-12-10T11:50:43.184518Z  INFO reth::node::events: Executing stage pipeline_stages=3/13 stage=Bodies checkpoint=60000 target=494557 progress=12.13% eta=unknown
2023-12-10T11:50:43.184519Z TRACE downloaders::bodies: Download range already in progress range=60001..=494557
2023-12-10T11:50:43.184527Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.184533Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.184680Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.184696Z DEBUG sync::stages::bodies: Commencing sync stage_progress=60001 target=494557 start_tx_id=49770
2023-12-10T11:50:43.184725Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.184790Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.184827Z TRACE sync::stages::bodies: Writing blocks bodies_len=1000
2023-12-10T11:50:43.184888Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.184925Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.185018Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.185294Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.185325Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.185350Z TRACE tokio_util::codec::framed_impl: writing; remaining=6672
2023-12-10T11:50:43.185396Z TRACE tokio_util::codec::framed_impl: writing; remaining=6672
2023-12-10T11:50:43.185481Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.185526Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.185565Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.185614Z TRACE tokio_util::codec::framed_impl: flushing framed transport
2023-12-10T11:50:43.185704Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.185659Z TRACE tokio_util::codec::framed_impl: framed transport flushed
2023-12-10T11:50:43.207824Z TRACE sync::metrics: Metric event received event=StageCheckpoint { stage_id: Bodies, checkpoint: StageCheckpoint { block_number: 61000, stage_checkpoint: Some(Entities(EntitiesCheckpoint { processed: 61001, total: 494558 })) }, max_block_number: Some(494557) }
2023-12-10T11:50:43.207851Z  INFO reth::node::events: Stage committed progress pipeline_stages=3/13 stage=Bodies checkpoint=61000 target=494557 progress=12.33% eta=unknown
2023-12-10T11:50:43.233130Z TRACE sync::pipeline: Pipeline finished tip=Some(0x99dad017823cc7c112176435b8e721a81c002267984f2d76fbb428bd95ec668f) result=Err(Provider(Database(Commit(998))))
2023-12-10T11:50:43.234647Z TRACE blockchain_tree: Returning canonical tip
2023-12-10T11:50:43.236104Z TRACE consensus::engine: Pipeline finished result=Err(Provider(Database(Commit(998)))) reached_max_block=false
2023-12-10T11:50:43.237100Z TRACE reth::cli: Saving current peers peers_file="C:\\Users\\Windows\\AppData\\Roaming\\reth\\holesky\\known-peers.json" num_peers=13443
2023-12-10T11:50:43.237932Z  INFO reth::cli: Wrote network peers to file peers_file="C:\\Users\\Windows\\AppData\\Roaming\\reth\\holesky\\known-peers.json"
Error: failed to commit transaction changes (998)

Location:
    C:\Users\Windows\Desktop\reth\bin\reth\src\node\mod.rs:581:9
```

**Comment by ControlCplusControlV** [comment] 2023-12-14 16:07
@kaliubuntu0206 brother is it you?

**Comment by kaliubuntu0206** [comment] 2023-12-14 18:19
Tried to fix the issue by switching the toolchain to `x86_64-pc-windows-gnu` which seems to be a correct one and the one supported by jemalloc https://github.com/gnzlbg/jemallocator#platform-support

1. c-kzg bindings from EF complained about the wrong flag specified https://github.com/ethereum/c-kzg-4844/pull/354#issuecomment-1856355981

2. jemallocator bindings also complained that `sh` is missing. Since windows doesn't use shell script I think it should be fixed from the bindings as well.

**Comment by kaliubuntu0206** [comment] 2023-12-16 20:19
I have compiled reth on linux without the default features using `--no-default-features` flag.

And it didn't returned a single error with Database which means that the error code 998 has nothing to do with jemalloc

**Comment by DaniPopes** [comment] 2023-12-28 14:38
@kaliubuntu0206 the jemalloc feature is a no-op on Windows, the system allocator is used instead.

**Comment by kaliubuntu0206** [comment] 2023-12-31 14:24
@DaniPopes Yes, and seems like jemalloc is not relevant with this issue, any clues to fix this?

**Comment by onbjerg** [comment] 2024-04-19 18:17
@ControlCplusControlV Sorry, it's been a while. Is this still happening? We've had a lot of releases since the issue was posted and have not run into it ourselves

**Comment by ControlCplusControlV** [comment] 2024-04-19 22:31
No worries, tbh I'm not sure if it still exits? Do you have a windows machine to test against?

**Comment by onbjerg** [comment] 2024-04-23 18:47
I've tried to reproduce in a Windows VM but couldn't, I'd assume it's been fixed since. I'll close the issue because of that, but please ping me if you ever encounter it again. We've also disabled jemalloc in some cases where we know it doesn't work

**Closed by onbjerg** 2024-04-23 18:47 UTC
Labels: C-bug, O-windows, S-needs-investigation, A-staged-sync, A-db
