### ISSUE TITLE
bug(rpc): `insufficient funds for gas` error on `trace_block`

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#11272] opened 2024-09-27 06:52 UTC
## Description

Calling `trace_block` for [holesky block 2402609](https://holesky.etherscan.io/block/2402609) results in `server returned an error response: error code -32003: insufficient funds for gas * price + value: have 3415642277587608 want 3465300072891260`.

## Steps To Reproduce

```sh
$ cast rpc trace_block 0x24A931
```

**Comment by mattsse** [comment] 2024-09-28 08:09
so what happens here is that there's a fee mismatch because this tx's sender is the fee recipient.
this is caused by this tx https://holesky.etherscan.io/tx/0x6bec6c70e59916558b65a39d2f4703f883dbf8248c809ec47c0d78e8742bcd14 that interacts with the beacon root system contract.
but we currently don't apply the 4788 system call in rpc tracing

this can be fixed by applying

https://github.com/paradigmxyz/reth/blob/50265b15db0789862dcae67dc462b565dab3d94d/crates/evm/src/system_calls/eip4788.rs#L137-L137

before we start tracing

**Closed** 2024-10-02 12:01 UTC
Labels: C-bug, A-rpc
