### ISSUE TITLE
`InMemorySize` super trait

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12589] opened 2024-11-15 19:57 UTC
### Describe the feature

Add `InMemorySize` as super trait for `reth-primitives-traits` traits: `Receipt`, `SignedTransaction` and `TxType`.

**Comment by Gerson2102** [comment] 2024-11-15 22:13
Hey I would like to work on this one.

**Comment by Gerson2102** [comment] 2024-11-17 21:15
You guys should moderate a little when someone is just opening a PR when the issue is not assigned to them. @emhane

**Comment by tuantran1702** [comment] 2024-11-18 02:45
> You guys should moderate a little when someone is just opening a PR when the issue is not assigned to them. [@emhane](https://github.com/emhane)

It’s open source environment, anyone can open a PR and you have no right to complain unless they steal your code.

**Closed** 2024-11-18 12:10 UTC
Labels: D-good-first-issue, A-sdk
