### ISSUE TITLE
Unusual amount of ECIES `TagCheckDecryptFailed` errors on incoming connections

### ISSUE THREAD

**Issue by jonasbostoen** [paradigmxyz/reth#710] opened 2023-01-04 09:16 UTC
### Describe the bug

It seems like every incoming connection I get is broken off with `ECIESErrorImpl::TagCheckDecryptFailed`. This happens in 
the following code in `decrypt_message`:
https://github.com/paradigmxyz/reth/blob/3a67809cb730e63de8a37e1da6928f3a509d83b1/crates/net/ecies/src/algorithm.rs#L226-L229

Relevant example of a trace:
```text
2023-01-03T16:56:43.645163Z TRACE net::session: new pending incoming session remote_addr=5.161.135.177:21712 session_id=SessionId(140)
2023-01-03T16:56:43.645207Z TRACE net: Incoming connection session_id=SessionId(140) remote_addr=5.161.135.177:21712
2023-01-03T16:56:43.645332Z DEBUG incoming{peer="Some(5.161.135.177:21712)"}: reth_ecies::stream: incoming ecies stream ...
2023-01-03T16:56:43.646252Z TRACE incoming{peer="Some(5.161.135.177:21712)"}:decode{peer="None" state="Auth"}: reth_ecies::codec: parsing auth
2023-01-03T16:56:43.646384Z  WARN net::session: ecies auth failed error=TagCheckDecryptFailed session_id=SessionId(140) remote_addr=5.161.135.177:21712
2023-01-03T16:56:43.646395Z  WARN net: Incoming pending session failed remote_addr=5.161.135.177:21712 error=Some(Ecies(TagCheckDecryptFailed))
2023-01-03T16:56:43.646406Z DEBUG net: Banning discovery ip=5.161.135.177
```

This is an example of the inputs to that function:
```
mac_key = 0x3ec16ddf13133bcc3bc2b07d4bde38956d68beb26b3b21277f7bf34100880999
iv = 0xa0cc193f8bb59cda4c7b6e6eaf2bdf63
encrypted_data = 0xc5071e8681b03fbdfee829caaaac456e75167510641739505d275b009aec53b1e2f5c686518dd50c20abddb515c3002cce231bcfb8689e824fe9ae40ee0d7d06ebb37a136f1aa03bd2dc28b64b46ca08515d0399b6acf403c0c1d6e9cac0c875fb5a24bf000d73bda60032373b13c92282f32128e41edd275dac921f9ffa83d99d95a3b99a4ad95a7dc955ff2c842d85250baf1469291ea9e9714f6182594bdf1f17b1450e317535d1c8e1b712fd952eb564800b3aaa6cf1dc7b03770ddc0d1e472f0ef472eccf7f31523b2abb2c8443291ead9301110278171b0e526e0b10c245ecc65039442f10243ae43556f961f12193aabd6896e986312d5928dce3b8d4f772cf0b174ef5b2db62debde00536fed3b8b954795a93f583e79d88b0b90f84d51d27c1f5fc510588e52eef36bc1979ba86b25303316c1f612521cf8dd952b4d7da4c7c16eeb699e6a6b76d123c979e323e4e9a709e90411e8c5c72dd59a4cbc1de033045830360f8127e21902151d8ab7540c5998afe5a3ddfd696fad4f19d27906070dc36f8c6c21e34b27b2636474d5f3983e9fbaa73ba72225b9c761a5aaefcef43b57af1ca40279159de00aa6da7efbc22d648879d17b24cece1
auth_data = 0x022e
```
### Steps to reproduce

Run the node with relevant ports open to allow for incoming connections

### Platform(s)

Linux (x86)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment] 2023-01-21 15:40
I think we can close this @Rjected since this appears to be due to high amount of useless peers on the network?

**Comment by Rjected** [comment] 2023-01-21 21:12
@mattsse yeah, going to close

**Comment by Rjected** [comment] 2023-03-14 20:17
This will be easier to repro locally once #1753 is in, but the basic setup would be running two reth nodes, and connecting them:
```bash
RUST_LOG=reth_ecies=trace,net::session=trace,net=trace reth node --disable-discovery --http --http.port 8545
```
In another shell:
```bash
LOCAL_ENODE=$(curl --location 'localhost:8545' --header 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"admin_nodeInfo", "params":[], "id":1 }' | jq '.result.enode' -r)
# replace the IP in the enode if necessary
reth node --disable-discovery --trusted-peers $LOCAL_ENODE

**Comment by Rjected** [comment] 2023-04-13 16:24
Confirmed that this is only caused by peers connecting with a stale `PeerId` / pubkey, and failing the pending session on `TagCheckDecrypt` is the right thing to do here

**Comment by Rjected** [comment] 2023-04-26 17:31
I started getting this error, here is some context:

We do have incoming connection tests from both from reth and geth nodes, which pass.

The `TagCheckDecryptFailed` error happens here:
https://github.com/paradigmxyz/reth/blob/57a19f91f0eebeb3952a260c28412494701d4ede/crates/net/ecies/src/algorithm.rs#L234-L237

The tag is created here:
https://github.com/paradigmxyz/reth/blob/57a19f91f0eebeb3952a260c28412494701d4ede/crates/net/ecies/src/algorithm.rs#L212-L213

This check is described in the ECIES portion of the RLPx spec:
https://github.com/ethereum/devp2p/blob/master/rlpx.md#ecies-encryption

> Bob verifies the authenticity of the message by checking whether `d == MAC(sha256(kM), iv || c)` then obtains the plaintext as `m = AES(kE, iv || c)`.

This is a simple MAC tag check, and could fail for the following reasons:
 * A bug in either side's MAC or ECDH implementation
 * A bug in either side's ECIES handshake implementation
 * Incoming peer uses the wrong peer id to generate the shared secret before initiating the connection

**Comment by onbjerg** [comment] 2023-05-29 14:00
I don't think this is still the case, so closing, feel free to re-open @mattsse / @Rjected / @gakonst if still the case

**Closed by onbjerg** 2023-05-29 14:00 UTC
Labels: C-bug, A-devp2p, A-networking

**Comment by gakonst** [comment] 2023-05-29 20:06
Yeah I think when encountered it has to do with bad peers and not with us.
