### ISSUE TITLE
op-reth base sync stalling

### ISSUE THREAD

**Issue by slordua** [paradigmxyz/reth#7477] opened 2024-04-05 06:00 UTC
### Describe the bug

sync stalls intermittently, and will continue syncing if i kill reth and op-node & restart. ~~reth logs aren't giving any clues at this point~~ (wasn't running debug level, sorry), just that contact is lost with consensus layer

### Steps to reproduce

```shell
op-reth node \
 --ipcpath ./ipc/base.ipc \
 --datadir ./base \
 --chain base \
 --rollup.sequencer-http https://mainnet-sequencer.base.org \
 --authrpc.port 9551 \
 --port 30304 \
 --discovery.port 30304 \
 --http \
 --http.port 9545 \
 --http.api trace,web3,eth,debug,eth-call-bundle \
 --ws \
 --ws.port 9546 \
 --ws.api trace,web3,eth,debug,eth-call-bundle \
 --metrics localhost:8453 \
 --log.file.directory ./log
 
 op-node \
 --l1=http://localhost:8545 \
 --l1.beacon=http://localhost:5052 \
 --l2=http://localhost:9551 \
 --network=base-mainnet \
 --rpc.addr=0.0.0.0 \
 --rpc.port=7000 \
 --l2.jwt-secret=../reth/base/jwt.hex \
 --l1.trustrpc=true
 ```

### Node logs

```text
// op-node

Apr 04 19:46:14 slorduA op-node[1711131]: t=2024-04-04T19:46:14-0700 lvl=eror msg="cancelling old block sealing job" payload=0x42e07b4405d8dd31
Apr 04 19:46:14 slorduA op-node[1711131]: t=2024-04-04T19:46:14-0700 lvl=eror msg="deposit only block was invalid" parent=0x8822e9794a802bb89e4a1ececed3e4cac72df39dca39c0ad9c69b1ddecd6b609:212100 err="failed to complete building on top of L2 chain 0x8822e9794a802bb89e4a1ececed3e4cac72df39dca39c0ad9c69b1ddecd6b609:212100, id: 0x42e07b4405d8dd31, error (3): updated forkchoice, but node is syncing"
Apr 04 19:46:14 slorduA op-node[1711131]: t=2024-04-04T19:46:14-0700 lvl=eror msg="Derivation process critical error" err="engine stage failed: crit: failed to process block with only deposit transactions: failed to complete building on top of L2 chain 0x8822e9794a802bb89e4a1ececed3e4cac72df39dca39c0ad9c69b1ddecd6b609:212100, id: 0x42e07b4405d8dd31, error (3): updated forkchoice, but node is syncing"
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.5
Commit SHA: VERGEN_IDEMPOTENT_OUTPUT
Build Timestamp: 2024-04-04T23:27:45.215291301Z
Build Features: jemalloc,optimism
Build Profile: release

op-node version v0.0.0-ac5b061d-1711143126

### What database version are you on?

2

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

per reth book, beta5 tag

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by zilayo** [comment] 2024-04-07 18:11
same issue - https://github.com/paradigmxyz/reth/issues/7500

**Comment by emhane** [comment] 2024-05-17 14:37
did you try out temp solutions proposed by users in https://github.com/paradigmxyz/reth/issues/7500 and did this solve your issue @slordua ?

**Comment by slordua** [comment] 2024-05-17 18:09
@emhane you can close this

```toml
[prune]
block_interval = 999999999
```

this worked for me

**Comment by emhane** [comment] 2024-05-18 13:51
closing, duplicate of https://github.com/paradigmxyz/reth/issues/7500

**Closed by emhane** 2024-05-18 13:51 UTC
Labels: C-bug, A-staged-sync, A-op-reth
