### ISSUE TITLE
Error: failed to commit transaction changes (998)

### ISSUE THREAD

**Issue by lucyzhang314** [paradigmxyz/reth#6045] opened 2024-01-12 18:33 UTC
### Describe the bug

![企业微信截图_17050841017897](https://github.com/paradigmxyz/reth/assets/40690755/d88dea76-2813-4a29-be3e-0005f56ead03)

### Steps to reproduce

1 Start .\reth.exe node --datadir . --debug.tip 0x92bff8886f0b158c133a5bcc7b8d108eab1563536ce42eea881cd6a54e9b0426 --authrpc.port 8552

### What version/commit are you on?

PS C:\reth> ./reth --version reth Version: 0.1.0-alpha.14 Commit SHA: 9d8fbd3a Build Timestamp: 2024-01-12T18:22:06.627061600Z Build Features: default,jemalloc Build Profile: release PS C:\reth>

### What database version are you on?

PS C:\reth> ./reth db version
Current database version: 1
Local database version: 1
PS C:\reth>

PS C:\reth> ./reth --version
reth Version: 0.1.0-alpha.14
Commit SHA: 9d8fbd3a
Build Timestamp: 2024-01-12T18:22:06.627061600Z
Build Features: default,jemalloc
Build Profile: release
PS C:\reth>

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

no

### If you've built Reth from source, provide the full command you used

 cargo build --release

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by lucyzhang314** [comment] 2024-01-17 22:32
![image](https://github.com/paradigmxyz/reth/assets/40690755/f20e9df8-5fa9-4607-bc7a-48ddef1ac555)

**Comment by cheddiefender** [comment] 2024-01-21 10:58
i'm having the same issue. did you ever figure it out?

**Comment by DaniPopes** [comment] 2024-01-22 16:16
Duplicate of https://github.com/paradigmxyz/reth/issues/3793.

**Closed by DaniPopes** 2024-01-22 16:16 UTC
Labels: C-bug, S-needs-triage
