### ISSUE TITLE
Invalid value 'goerli' for '--chain <CHAIN_OR_PATH>': missing field `daoForkBlock`

### ISSUE THREAD

**Issue by bergkvist** [paradigmxyz/reth#1487] opened 2023-02-21 18:42 UTC
### Describe the bug

Node fails to start on goerli testnet (though it seems to work for sepolia)

### Steps to reproduce

```sh
$ cargo build --release

# Seems to work
$ ./target/release/reth node --chain sepolia

# Fails to start
$ ./target/release/reth node --chain goerli
error: Invalid value 'goerli' for '--chain <CHAIN_OR_PATH>': missing field `daoForkBlock` at line 16 column 3
```

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

ade1ea4216136e05b02585e1168ea154fd08988f (stable branch)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment] 2023-02-21 19:42
hmm I wasn't able to reproduce this on main:

```
../../target/debug/reth node --chain goerli                                                                                                                                                                             $ matt/add-chain-parse-test 
2023-02-21T19:41:51.392538Z  INFO reth 0.1.0 starting
2023-02-21T19:41:51.401420Z  INFO Configuration loaded path=/Users/Matthias/Library/Application Support/reth/db
2023-02-21T19:41:51.401458Z  INFO Opening database path=/Users/Matthias/Library/Application Support/reth/db
2023-02-21T19:41:51.407307Z  INFO Database opened
2023-02-21T19:41:51.409626Z  WARN warn_msg="No tip specified. reth cannot communicate with consensus clients, so a tip must manually be provided for the online stages with --debug.tip <HASH>."
2023-02-21T19:41:51.409918Z  INFO Consensus engine initialized
2023-02-21T19:41:51.409944Z  INFO Connecting to P2P network
2023-02-21T19:41:51.436489Z  INFO Connected to P2P network peer_id=0x901e…7f9a local_addr=0.0.0.0:30303
2023-02-21T19:41:51.438854Z  INFO Started RPC server
2023-02-21T19:41:51.451327Z  INFO Starting sync pipeline
2023-02-21T19:41:51.452666Z  INFO Executing stage stage=Headers
2023-02-21T19:41:51.453057Z  INFO Status connected_peers=0 stage=Headers checkpoint=0

```

**Comment by mattsse** [comment] 2023-02-21 19:45
oh your linked commit is over a month old?

**Comment by bergkvist** [comment] 2023-02-21 20:15
Yeah, latest version from stable branch

**Comment by gakonst** [comment] 2023-02-22 21:24
Could not reproduce on latest `main`, and we provide no stability guarantees yet! Closing..

**Closed by gakonst** 2023-02-22 21:24 UTC
Labels: C-bug, A-cli
