### ISSUE TITLE
Execution stage progress reporting starts at 100% 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#6140] opened 2024-01-19 23:55 UTC
### Describe the bug

incorrect 100% reporting at transition into execution stage

```
2024-01-19T23:50:56.937875Z  INFO reth::commands::node::events: Executing stage pipeline_stages=4/13 stage=SenderRecovery checkpoint=765769 target=771292 stage_progress=100.00% stage_eta=unknown
2024-01-19T23:51:00.984839Z  INFO reth::commands::node::events: Forkchoice updated head_block_hash=0x8ca448535b9a06452dc16c36d6e15642f859af84e2ae606dff77ffa6e7da2c27 safe_block_hash=0xf780d11707a3db8d167e5bc3f19a22d8da8ee9936f2367dc2d99e3f72fd0e9c8 finalized_block_hash=0x4e0d95e557f5618567826484ee2477f06044cb6dc4dad96957de45810527b0df status=Syncing
2024-01-19T23:51:03.460903Z  INFO reth::commands::node::events: Stage finished executing pipeline_stages=4/13 stage=SenderRecovery checkpoint=771292 target=771292 stage_progress=100.00% stage_eta=unknown
2024-01-19T23:51:03.559389Z  INFO reth::commands::node::events: Executing stage pipeline_stages=5/13 stage=Execution checkpoint=765769 target=771292 stage_progress=100.00%
2024-01-19T23:51:05.237379Z  INFO reth::cli: Status connected_peers=1 freelist=126138 stage=Execution checkpoint=765769 target=771292 stage_progress=100.00%
....
2024-01-19T23:52:03.294980Z  INFO reth::commands::node::events: Stage finished executing pipeline_stages=5/13 stage=Execution checkpoint=771292 target=771292 stage_progress=100.00%

```

looks like the initial % calc is wrong if there's one batch

### Steps to reproduce

-

### What type of node are you running?

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by pistomat** [comment] 2024-02-07 15:44
+1 I am also having this issue.

**Comment by shekhirin** [comment] 2024-02-13 13:21
So I believe the issue is that when processing the `PipelineEvent::Run`, we grab the `checkpoint` from previous execution https://github.com/paradigmxyz/reth/blob/9814d3c0dda9b073f783080e9ce9a3139c82be86/bin/reth/src/commands/node/events.rs#L73-L89
 which means that it contains the outdated progress (which is gas processed for the `Execution` stage).

When processing the `PipelineEvent::Ran`, we have new checkpoint coming from the fresh execution https://github.com/paradigmxyz/reth/blob/9814d3c0dda9b073f783080e9ce9a3139c82be86/bin/reth/src/commands/node/events.rs#L114-L130 and it should contain the up-to-date information.

I would suggest we remove the `stage_progress` field from `Executing stage` message and leave only `checkpoint` and `target`. For `Stage committed progress` and `Stage finished executing` messages, we can leave the `stage_progress` as-is.

**Closed** 2024-02-13 13:57 UTC
Labels: C-bug, A-observability
