### ISSUE TITLE
hive devp2p test TestSameRequestID is flaky

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#2030] opened 2023-03-29 20:15 UTC
### Describe the bug
Hive test `TestSameRequestID` logs:
```
not ok 4 TestSameRequestID
# header mismatch: 
# expected [0xc00027f680 0xc00027f8c0] 
# got &{1234 [0xc00027e900 0xc00027eb40]}
```

The test is implemented here:
https://github.com/ethereum/go-ethereum/blob/7ca4f60a1abd2a8c9df2ed9ae35a891b0ac9e464/cmd/devp2p/internal/ethtest/suite.go#L214

The `1234` is the request ID, so this might be related to how the message is being downcast, or we may be just returning the wrong response:
https://github.com/ethereum/go-ethereum/blob/7ca4f60a1abd2a8c9df2ed9ae35a891b0ac9e464/cmd/devp2p/internal/ethtest/suite.go#L252-L262

### Steps to reproduce

[Run hive](#851):
```
./hive --client reth --sim devp2p
```
I couldn't figure out how to run this test on its own, and I have not been able to reproduce this locally, so I'm not sure why this is flaking on CI

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment] 2023-03-30 07:47
no the issue is that we expect messages to be unique, tbh I'm not sure what to make of this test because it reads like request ids don't have to be unique which kinda defeats their purpose?

**Comment by mattsse** [comment] 2023-06-20 14:49
I executed `TestSameRequestID` in a script and never got a failure, so I'm closing this optimistically

**Closed by mattsse** 2023-06-20 14:49 UTC
Labels: C-bug, S-needs-investigation, C-test
